version: "3.9"
volumes:
  data_api:
  data_ssh:
  MongoOFVp:
services:
  # Mongo Apps and Server
  mongodb:
    build: https://raw.githubusercontent.com/prisma/prisma/main/docker/mongodb_replica/Dockerfile
    restart: always
    ports:
      - 27017:27017/tcp
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ofvpuser
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
  mongo-express:
    image: mongo-express
    # restart: always
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: devpass
      ME_CONFIG_MONGODB_URL: "mongodb://root:ofvpuser@mongodb:27017"

  # OFVp
  ofvp_daemon_maneger:
    image: ghcr.io/ofvp-project/deamonmaneger:next
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      # NODE_ENV: "development"
      MongoDB_URL: "mongodb://root:ofvpuser@mongodb:27017"
      PASSWORD_ENCRYPT: "dev"
      COOKIE_SECRET: "dev"
      DAEMON_USERNAME: ""
      DAEMON_PASSWORD: ""
    ports:
      - 3000:3000/tcp
    volumes:
      - data_api:/data

  ofvp_openssh:
    build:
      dockerfile: Dockerfile
    environment:
      PASSWORD_ENCRYPT: "dev"
      DAEMON_HOST: "http://ofvp_daemon_maneger:5000"
      DAEMON_USERNAME: ""
      DAEMON_PASSWORD: ""
    ports:
      - 2222:22/tcp
    volumes:
      - data_ssh:/data