version: "3.9"
networks:
  defaultOfvpNetwork:
volumes:
  mongoStorage:
  sshStorage:

services:
  mongodb:
    image: mongo
    restart: always
    command: "--bind_ip_all --port 27017 --noauth --quiet --logpath /dev/null"
    networks: [defaultOfvpNetwork]
    volumes: [mongoStorage:/data/db]
  maneger:
    image: ghcr.io/ofvp-project/maneger:next
    ports: [3000:3000/tcp]
    networks: [defaultOfvpNetwork]
    depends_on: [mongodb]
    environment:
      NODE_ENV: "development"
      MONGO_URL: "mongodb://mongodb:27017/ofvp"
      PASSWORD_SECERET: "dev"
      COOKIE_SECRET: "dev"

  ssh:
    image: ghcr.io/ofvp-project/ssh-server:next
    build: ./
    restart: always
    depends_on: [ofvpmaneger]
    networks: [defaultOfvpNetwork]
    ports: [8022:22/tcp]
    volumes: [sshStorage:/data]
    environment:
      NODE_ENV: "development"
      MONGO_URL: "mongodb://mongodb:27017/ofvp"
      PASSWORD_SECERET: "dev"

  webproxy:
    image: ghcr.io/ofvp-project/webproxy:latest
    restart: always
    depends_on: [ssh]
    networks: [defaultOfvpNetwork]
    ports: [8080:80/tcp]
    command: "-l 1 --ssh ssh:22"