version: "3.9"
networks:
  defaultOfvpNetwork:
volumes:
  mongoStorage:

services:
  mongodb:
    image: mongo
    restart: always
    command: "--bind_ip_all --port 27017 --noauth --quiet --logpath /dev/null"
    networks: [defaultOfvpNetwork]
    volumes: [mongoStorage:/data/db]
  ofvpmaneger:
    image: ghcr.io/ofvp-project/deamonmaneger:next
    ports: [3000:3000/tcp]
    networks: [defaultOfvpNetwork]
    depends_on: [mongodb]
    environment:
      NODE_ENV: "development"
      MongoDB_URL: "mongodb://mongodb:27017/ofvp"
      PASSWORD_ENCRYPT: "dev"
      COOKIE_SECRET: "dev"
      DAEMON_USERNAME: ""
      DAEMON_PASSWORD: ""

  ofvp_openssh:
    build: .
    restart: on-failure
    depends_on: [ofvpmaneger]
    networks: [defaultOfvpNetwork]
    ports: [2222:22/tcp]
    environment:
      PASSWORD_ENCRYPT: "dev"
      DAEMON_HOST: "http://ofvpmaneger:5000"
      DAEMON_USERNAME: ""
      DAEMON_PASSWORD: ""