version: "3.9"
networks:
  defaultOfvpNetwork:
volumes:
  mongoStorage:
  sshStorage:

services:
  mongodb:
    image: mongo
    restart: always
    command: "--bind_ip_all --port 27017 --noauth --quiet --logpath /dev/null"
    networks: [defaultOfvpNetwork]
    volumes: [mongoStorage:/data/db]
  ofvpmaneger:
    image: ghcr.io/ofvp-project/deamonmaneger:next
    ports: [3000:3000/tcp]
    networks: [defaultOfvpNetwork]
    depends_on: [mongodb]
    environment:
      NODE_ENV: "development"
      MongoDB_URL: "mongodb://mongodb:27017/ofvp"
      PASSWORD_ENCRYPT: "dev"
      COOKIE_SECRET: "dev"
      DAEMON_USERNAME: ""
      DAEMON_PASSWORD: ""

  ssh:
    build: ./
    restart: always
    depends_on: [ofvpmaneger]
    networks: [defaultOfvpNetwork]
    ports: [2222:22/tcp]
    volumes: [sshStorage:/data]
    environment:
      PASSWORD_ENCRYPT: "dev"
      NODE_ENV: "development"
      DAEMON_HOST: "http://ofvpmaneger:5000"
      DAEMON_USERNAME: ""
      DAEMON_PASSWORD: ""

  webproxy:
    image: ghcr.io/ofvp-project/webproxy:latest
    restart: always
    depends_on: [ssh]
    networks: [defaultOfvpNetwork]
    ports: [8080:80/tcp]
    command: "-l 1 --ssh ssh:22"
