name: Publish docker image
on:
  push:
    branches:
      - main
  release:
    types:
      - released

jobs:
  releaseNext:
    runs-on: ubuntu-latest
    name: Publish docker image
    steps:
      - uses: actions/checkout@v3.2.0

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login into registry Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: ${{ secrets.DOCKER_TARGERTS }}
          cache-from: type=gha,scope=${{ github.ref }}_ofvp_sshserver_${{ github.repository }}
          cache-to: type=gha,mode=max,scope=${{ github.ref }}_sshserver_${{ github.repository }}
          tags: ghcr.io/sirherobrine23/nodesshserver:${{ github.event.release && 'latest' || 'next' }}